services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
    #      - 'POSTGRES_PASSWORD=xd' TODO haslo login jak do kola
    #      - 'POSTGRES_USER=xd'     TODO haslo login jak do kola
    ports:
      - '34250:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql