version: '3.8'

services:
  postgres-database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '34250:5432'
    volumes:
      - ./src/main/resources/db/schema-init.sql:/docker-entrypoint-initdb.d/schema-init.sql
