###
Wypisane wszystkie endpointy (podstawowe htttp do manualego testowania)
###
POST http://localhost:9090/register
Content-Type: application/json

{
  "login": "test6",
  "password": "test"
}


###
POST http://localhost:9090/login
Content-Type: application/json

{
  "login": "test",
  "password": "test"
}


###
POST http://localhost:9090/patient/new
Content-Type: application/json
Authorization: Bearer {{JWT_token}}

{
  "socialSecurityNumber": "35655111113",
  "firstName": "Kamil",
  "lastName": "Golawski",
  "birthDate": "2003-01-17T10:00:00",
  "address": "Lublin",
  "phoneNumber": "123456789",
  "email": "test@gmail.com",
  "age": 21,
  "gender": "MALE"
}


###
POST http://localhost:9090/medical-case/new
Content-Type: application/json
Authorization: Bearer {{JWT_token}}

{
  "patientId": 1,
  "admissionReason": "testowe pod wieczor",
  "admissionDate": "2026-07-10T10:00:00",
  "description": "test",
  "attendingDoctorId": 1
}


###
POST http://localhost:9090/doctor/new/treatment
Content-Type: application/json
Authorization: Bearer {{JWT_token}}

{
  "description": "test test",
  "startDate": "2025-07-10T10:00:00",
  "endDate": "2025-07-20T15:00:00",
  "name": "Test",
  "details": "test test",
  "medicalCaseId": 103,
  "medicalDoctorId": 1
}

###
PATCH http://localhost:9090/doctor/treatment/1/status
Content-Type: application/json
Authorization: Bearer {{JWT_token}}

{
  "status": "CANCELLED"
}


###
POST http://localhost:9090/doctor/new/medication
Content-Type: application/json
Authorization: Bearer {{JWT_token}}

{
  "name": "Tescior123",
  "startDate": "2026-07-10",
  "endDate": "2025-07-20",
  "details": "xd",
  "medicalCaseId": 103,
  "medicalDoctorId": 1,
  "dosageForm": "1x1",
  "strength": "200mg",
  "unit": "tabletki"
}

###
PATCH http://localhost:9090/doctor/medication/10/status
Content-Type: application/json
Authorization: Bearer {{JWT_token}}

{
  "status": "CANCELLED"
}


###
GET http://localhost:9090/medical-case/113dpTaKev/summary
Content-Type: application/json
Authorization: Bearer {{JWT_token}}


###
GET http://localhost:9090/medical-case/103/treatment/all
Accept: application/json
Authorization: Bearer {{JWT_token}}


###
GET http://localhost:9090/medical-case/103/medication/all
Accept: application/json
Authorization: Bearer {{JWT_token}}


###
GET http://localhost:9090/patient/QSv9M3gU4n
Accept: application/json
Authorization: Bearer {{JWT_token}}


###
PATCH http://localhost:9090/medical-case/103
Accept: application/json
Authorization: Bearer {{JWT_token}}


###
GET http://localhost:9090/doctor/patient/all
Accept: application/json
Authorization: Bearer {{JWT_token}}


###
GET http://localhost:9090/doctor/medical-case/all
Accept: application/json
Authorization: Bearer {{JWT_token}}

###
POST http://localhost:9090/patient/restart
Content-Type: application/json
Authorization: Bearer {{JWT_token}}

{
  "email": "test@gmail.com"
}
