name: Run tests

on:
  push:
    branches-ignore: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        working-directory: backend
        run: mvn clean install
      
      - name: Run tests
        working-directory: backend
        run: mvn test
      
      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: backend/target/surefire-reports
