name: Java CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        working-directory: backend
        run: mvn clean install
      
      - name: Run tests
        id: tests
        working-directory: backend
        run: mvn test
      
      - name: Check test results
        run: |
          if [[ "${{ steps.tests.outcome }}" == "failure" ]]; then
            echo "❌ Tests failed!"
            exit 1
          else
            echo "✅ Tests passed!"
          fi
      
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/target/surefire-reports
