name: Java CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      working-directory: backend
      run: mvn clean install
    - name: Run tests
      id: tests
      working-directory: backend
      run: mvn test
      
    - name: Check test results
      if: ${{ steps.tests.outcome == 'failure' }}
      run: exit 1
      
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: backend/target/surefire-reports
        
    - name: Notify Success
      if: ${{ steps.tests.outcome == 'success' }}
      run: echo "✅ Tests passed!"
      
    - name: Notify Failure  
      if: ${{ steps.tests.outcome == 'failure' }}
      run: echo "❌ Tests failed!"