name: Run tests

on:
  push:
    branches-ignore: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        working-directory: backend
        run: mvn clean install
      
      - name: Run tests
        id: test
        working-directory: backend
        continue-on-error: true 
        run: mvn test

      - name: Check test results
        run: |
          if [[ "${{ steps.test.outcome }}" == "success" ]]; then
            echo "Successs :)"
          else
            echo "Failure :("
          fi
      
      - name: Upload test results
        if: ${{ always() }} 
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: backend/target/surefire-reports
