name: Java CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      working-directory: backend
      run: mvn clean install
    - name: Run tests
      id: tests
      working-directory: backend
      run: |
        mvn test > test-results.txt

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/target/surefire-reports

    - name: Notify Success
      if: ${{ steps.tests.outcome == 'success' }}
      run: |
        echo "Tests passed! Commit can be merged safely."
        LAST_LINES=$(tail -n 10 backend/test-results.txt)
        gh issue create --title "Tests passed" --body "All tests have passed successfully. The commit can be merged. \n ${LAST_LINES}" --label "CI/CD" --assignee ${{ github.actor }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Notify Failure  
      if: ${{ steps.tests.outcome == 'failure' }}
      run: |
        echo "Tests failed! Please fix the issues before merging."
        LAST_LINES=$(tail -n 10 backend/test-results.txt)
        gh issue create --title "Tests failed" --body "Some tests have failed. Please fix the issues before merging the commit. \n ${LAST_LINES}" --label "CI/CD" --assignee ${{ github.actor }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
