###
### GET request to example server
### Login request
POST http://127.0.0.1:9090/login
Content-Type: application/json

{
  "login": "someUser8",
  "password": "somePassword"
}

###

GET http://127.0.0.1:9090/medicalData/yZbzDDFlL2/summary
Accept: application/json

###